nas_share_path: /home/sheldon/Documents/nas/share/Sheldon/Faresight/faresight.db
local_db_path: ~/.local/share/expense-tracker/local.db
sync_on_startup: true
sync_on_shutdown: true
sync_interval_minutes: 5

ollama_host: http://localhost:11434
ollama_model: llama3.2:3b
categorization_poll_interval_s: 10
page_size: 25
top_card_page_limit: 5

bank_logos:
  bank of america: bank-of-america.svg
  capital one: capital-one.jpeg
  chase: chase.svg
  american express: amex.svg
  fidelity: fidelity.svg
  sofi: sofi.jpeg
  betterment: betterment.svg
